name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}

    name: MagPy Test ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Create Psi4 Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: p4env
        environment-file: devtools/conda-envs/psi.yaml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: true

    - name: Install Psi4
      run: |
        conda info
        conda list --show-channel-urls
        hash -r
        env
        conda install psi4 python=${{ matrix.python-version }} -c conda-forge
        ls -l $CONDA

    - name: Test Psi4 Python Loading
      run: |
        export PATH=$CONDA_PREFIX/bin:$PATH
        export PYTHONPATH=$CONDA_PREFIX/lib:$PYTHONPATH
        conda env list
        python -c "import psi4"

    - name: Install MagPy and Deps
      run: |
        python -m pip install .
        pip install opt_einsum
        pip install pytest

    - name: Pytest
      run: |
        pytest -v --color=yes

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
